from .gpytorch_classif_bernoulli import GPyTorchClassificationBernoulliTrainer
from .gpytorch_classif_softmax import GPyTorchClassificationSoftmaxTrainer
from .pytorch_classif_deterministic import PyTorchClassificationDeterministicTrainer
from .pytorch_classif_laplace_approx import PyTorchClassificationLaplaceTrainer
from .pytorch_classif_mcdo import PyTorchClassificationMCDropoutTrainer
from .sklearn_neural_net import SKLearnNeuralNetClassificationTrainer
from .sklearn_random_forest_classif import SKLearnRandomForestClassificationTrainer
