# Supervised
python  main.py  --multirun  rng.seed=range(20)  experiment_name=cifar10_curated_supervised  data=cifar10/image_curated  model=pytorch_conv_net_resnet18_mcdo  trainer=pytorch_neural_net_classif_mcdo  trainer.n_optim_steps_min=5_000  acquisition.method=random
python  main.py  --multirun  rng.seed=range(20)  experiment_name=cifar10_curated_supervised  data=cifar10/image_curated  model=pytorch_conv_net_resnet18_mcdo  trainer=pytorch_neural_net_classif_mcdo  trainer.n_optim_steps_min=5_000  acquisition.method=bald
python  main.py  --multirun  rng.seed=range(20)  experiment_name=cifar10_curated_supervised  data=cifar10/image_curated  model=pytorch_conv_net_resnet18_mcdo  trainer=pytorch_neural_net_classif_mcdo  trainer.n_optim_steps_min=5_000  acquisition.method=epig

# Semi-supervised
python  main.py  --multirun  rng.seed=range(20)  experiment_name=cifar10_curated_semi     data=cifar10/embedding_curated    model=sklearn_random_forest_classif  trainer=sklearn_random_forest_classif  acquisition.method=random
python  main.py  --multirun  rng.seed=range(20)  experiment_name=cifar10_curated_semi     data=cifar10/embedding_curated    model=sklearn_random_forest_classif  trainer=sklearn_random_forest_classif  acquisition.method=bald
python  main.py  --multirun  rng.seed=range(20)  experiment_name=cifar10_curated_semi     data=cifar10/embedding_curated    model=sklearn_random_forest_classif  trainer=sklearn_random_forest_classif  acquisition.method=epig
python  main.py  --multirun  rng.seed=range(20)  experiment_name=cifar10_curated_semi     data=cifar10/embedding_curated    model=sklearn_random_forest_classif  trainer=sklearn_random_forest_classif  acquisition.method=greedy_k_centers  acquisition.batch_size=10
python  main.py  --multirun  rng.seed=range(20)  experiment_name=cifar10_curated_semi     data=cifar10/embedding_curated    model=sklearn_random_forest_classif  trainer=sklearn_random_forest_classif  acquisition.method=k_means           acquisition.batch_size=10
python  main.py  --multirun  rng.seed=range(20)  experiment_name=cifar10_curated_semi     data=cifar10/embedding_curated    model=sklearn_random_forest_classif  trainer=sklearn_random_forest_classif  acquisition.method=probcover         acquisition.batch_size=10
python  main.py  --multirun  rng.seed=range(20)  experiment_name=cifar10_curated_semi     data=cifar10/embedding_curated    model=sklearn_random_forest_classif  trainer=sklearn_random_forest_classif  acquisition.method=typiclust         acquisition.batch_size=10
python  main.py  --multirun  rng.seed=range(20)  experiment_name=cifar10_redundant_semi   data=cifar10/embedding_redundant  model=sklearn_random_forest_classif  trainer=sklearn_random_forest_classif  acquisition.method=random                                       adjust_test_predictions=True
python  main.py  --multirun  rng.seed=range(20)  experiment_name=cifar10_redundant_semi   data=cifar10/embedding_redundant  model=sklearn_random_forest_classif  trainer=sklearn_random_forest_classif  acquisition.method=bald                                         adjust_test_predictions=True
python  main.py  --multirun  rng.seed=range(20)  experiment_name=cifar10_redundant_semi   data=cifar10/embedding_redundant  model=sklearn_random_forest_classif  trainer=sklearn_random_forest_classif  acquisition.method=epig                                         adjust_test_predictions=True
python  main.py  --multirun  rng.seed=range(20)  experiment_name=cifar10_redundant_semi   data=cifar10/embedding_redundant  model=sklearn_random_forest_classif  trainer=sklearn_random_forest_classif  acquisition.method=greedy_k_centers  acquisition.batch_size=10  adjust_test_predictions=True
python  main.py  --multirun  rng.seed=range(20)  experiment_name=cifar10_redundant_semi   data=cifar10/embedding_redundant  model=sklearn_random_forest_classif  trainer=sklearn_random_forest_classif  acquisition.method=k_means           acquisition.batch_size=10  adjust_test_predictions=True
python  main.py  --multirun  rng.seed=range(20)  experiment_name=cifar10_redundant_semi   data=cifar10/embedding_redundant  model=sklearn_random_forest_classif  trainer=sklearn_random_forest_classif  acquisition.method=probcover         acquisition.batch_size=10  adjust_test_predictions=True
python  main.py  --multirun  rng.seed=range(20)  experiment_name=cifar10_redundant_semi   data=cifar10/embedding_redundant  model=sklearn_random_forest_classif  trainer=sklearn_random_forest_classif  acquisition.method=typiclust         acquisition.batch_size=10  adjust_test_predictions=True