python  main.py  --multirun  rng.seed=range(20)  experiment_name=magic_nn      data=uci/magic      model=pytorch_fc_net_mcdo_3layer     trainer=pytorch_neural_net_classif_mcdo  trainer.early_stopping_patience=10_000  trainer.optimizer.lr=0.1  acquisition.method=random
python  main.py  --multirun  rng.seed=range(20)  experiment_name=magic_nn      data=uci/magic      model=pytorch_fc_net_mcdo_3layer     trainer=pytorch_neural_net_classif_mcdo  trainer.early_stopping_patience=10_000  trainer.optimizer.lr=0.1  acquisition.method=bald
python  main.py  --multirun  rng.seed=range(20)  experiment_name=magic_nn      data=uci/magic      model=pytorch_fc_net_mcdo_3layer     trainer=pytorch_neural_net_classif_mcdo  trainer.early_stopping_patience=10_000  trainer.optimizer.lr=0.1  acquisition.method=epig
python  main.py  --multirun  rng.seed=range(20)  experiment_name=magic_rf      data=uci/magic      model=sklearn_random_forest_classif  trainer=sklearn_random_forest_classif                                                                      acquisition.method=random
python  main.py  --multirun  rng.seed=range(20)  experiment_name=magic_rf      data=uci/magic      model=sklearn_random_forest_classif  trainer=sklearn_random_forest_classif                                                                      acquisition.method=bald
python  main.py  --multirun  rng.seed=range(20)  experiment_name=magic_rf      data=uci/magic      model=sklearn_random_forest_classif  trainer=sklearn_random_forest_classif                                                                      acquisition.method=epig
python  main.py  --multirun  rng.seed=range(20)  experiment_name=satellite_nn  data=uci/satellite  model=pytorch_fc_net_mcdo_3layer     trainer=pytorch_neural_net_classif_mcdo  trainer.early_stopping_patience=10_000  trainer.optimizer.lr=0.1  acquisition.method=random
python  main.py  --multirun  rng.seed=range(20)  experiment_name=satellite_nn  data=uci/satellite  model=pytorch_fc_net_mcdo_3layer     trainer=pytorch_neural_net_classif_mcdo  trainer.early_stopping_patience=10_000  trainer.optimizer.lr=0.1  acquisition.method=bald
python  main.py  --multirun  rng.seed=range(20)  experiment_name=satellite_nn  data=uci/satellite  model=pytorch_fc_net_mcdo_3layer     trainer=pytorch_neural_net_classif_mcdo  trainer.early_stopping_patience=10_000  trainer.optimizer.lr=0.1  acquisition.method=epig
python  main.py  --multirun  rng.seed=range(20)  experiment_name=satellite_rf  data=uci/satellite  model=sklearn_random_forest_classif  trainer=sklearn_random_forest_classif                                                                      acquisition.method=random
python  main.py  --multirun  rng.seed=range(20)  experiment_name=satellite_rf  data=uci/satellite  model=sklearn_random_forest_classif  trainer=sklearn_random_forest_classif                                                                      acquisition.method=bald
python  main.py  --multirun  rng.seed=range(20)  experiment_name=satellite_rf  data=uci/satellite  model=sklearn_random_forest_classif  trainer=sklearn_random_forest_classif                                                                      acquisition.method=epig
python  main.py  --multirun  rng.seed=range(20)  experiment_name=vowels_nn     data=uci/vowels     model=pytorch_fc_net_mcdo_3layer     trainer=pytorch_neural_net_classif_mcdo  trainer.early_stopping_patience=10_000  trainer.optimizer.lr=0.1  acquisition.method=random
python  main.py  --multirun  rng.seed=range(20)  experiment_name=vowels_nn     data=uci/vowels     model=pytorch_fc_net_mcdo_3layer     trainer=pytorch_neural_net_classif_mcdo  trainer.early_stopping_patience=10_000  trainer.optimizer.lr=0.1  acquisition.method=bald
python  main.py  --multirun  rng.seed=range(20)  experiment_name=vowels_nn     data=uci/vowels     model=pytorch_fc_net_mcdo_3layer     trainer=pytorch_neural_net_classif_mcdo  trainer.early_stopping_patience=10_000  trainer.optimizer.lr=0.1  acquisition.method=epig
python  main.py  --multirun  rng.seed=range(20)  experiment_name=vowels_rf     data=uci/vowels     model=sklearn_random_forest_classif  trainer=sklearn_random_forest_classif                                                                      acquisition.method=random
python  main.py  --multirun  rng.seed=range(20)  experiment_name=vowels_rf     data=uci/vowels     model=sklearn_random_forest_classif  trainer=sklearn_random_forest_classif                                                                      acquisition.method=bald
python  main.py  --multirun  rng.seed=range(20)  experiment_name=vowels_rf     data=uci/vowels     model=sklearn_random_forest_classif  trainer=sklearn_random_forest_classif                                                                      acquisition.method=epig